name: CI

on: [push, pull_request]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Build project
      run: make

    - name: Lint with flake8
      run: flake8 .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: b2access-probe-py${{ matrix.python-version }}
        path: '*.tar.gz'
        if-no-file-found: 'error'
